name: 'Terraform'

on:
  push:
    branches:
    - master
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  terraform-versions:
    name: 'Terraform Versions' 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        terraform-versions: [0.11.14, 0.12.24]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform - ${{ matrix['terraform-versions'] }}
      uses: ./
      with:
        terraform_version: ${{ matrix['terraform-versions'] }}
    
    - name: Validate Teraform Version - ${{ matrix['terraform-versions'] }}
      run: terraform version | grep ${{ matrix['terraform-versions']}}
    
  terraform-run-local:
    name: 'Terraform Run Local' 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        working-directory: ./.github/workflows/data/local
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: ./
    
    - name: Terraform Init 
      shell: bash
      run: terraform init
    
    - name: Terraform Format 
      shell: bash
      run: terraform fmt -check
    
    - name: Terraform Plan 
      id: plan
      shell: bash
      run: terraform plan 

    - name: Print Terraform Plan 
      shell: bash
      run: echo "${{ steps.plan.outputs.stdout }}"
